### ISSUE TITLE
Folders opened with Open Folder are not saved

### ISSUE THREAD

**Issue by sryze** [Zren/atom-open-recent#1]
If you start Atom from the command line the folder is saved. But if you open a folder with Open Folder it's not saved.

**Comment by Zren** [comment]
Ah, they deprecated it.

https://github.com/atom/atom/blob/d26c19a0ec9a4c807b37995970c6ba83782189c1/src/workspace.coffee#L355

**Comment by Zren** [comment]
Hmm. Just reinstalled Atom (haven't been using it for awhile). Using v169, if you open Atom, then click `Open Folder...` while no project path is set, it will set the path of the current window instead of opening a new window (yay!). However, opening another folder while the project path is set, the new folder is added to the recent folders list.

Looks like the logic skips the `Workspace::open-uri` event and I'll need to listen for the `Project::path-changed` event.
