### ISSUE TITLE
[FEA] Pinned projects

### ISSUE THREAD

**Issue by jerone** [Zren/atom-open-recent#3]
Would be great if I could pin projects/files that I open a lot.

**Comment by Zren** [comment]
Tbh, I'm hesitant to diverge from the sublime text ui. If you just want an easy access to favourite projects, then project manager might be for you.

If that plugin isn't ideal, it looks like I could implement this feature. I did a small mockup

![](http://i.imgur.com/XtmW3jR.png)
- https://github.com/atom/atom-shell/blob/master/docs/api/menu.md
- https://github.com/atom/atom-shell/blob/master/docs/api/menu-item.md

Checkmarks aren't ideal UI wise, but it seems a hassle to use a custom icon (edit: should note that icon support was only added 2 days ago). I might possible be able to use unicode in the menuItem.label but meh.

### Edit

If we're diverging, we can even get fancy with sublabels (though it's just wasting vertical space heh).

![](http://i.imgur.com/CJ8kLxG.png)

### Edit

Might make Unpin a submenu with a the pinned paths, as otherwise it'd be ackward to unpin something without opening the path (which might no longer exist).

### Edit

![](http://i.imgur.com/iBY2aGU.png)

Radio buttons looked better as "pinned" objects.

**Comment by jerone** [comment]
Sorry, I didn't see your edits, but the fancy items looks great! If icons are allowed and Octicons are supported, I would suggest the ['pin'](https://octicons.github.com/icon/pin/) icon. Any other solution would do the trick too, I think it's very self explainable.

**Comment by jerone** [comment]
I saw you pushed some code to a separate [branch](https://github.com/Zren/atom-open-recent/tree/pin). Can I help with testing?

**Comment by jerone** [comment]
In an attempt to clean up my created issues that have not been processed or updated over a year, I'm closing this issue. If this issue is still relevant, please reopen another issue.
