### ISSUE TITLE
Show full filepath in menu

### ISSUE THREAD

**Issue by stebiger** [Zren/atom-open-recent#8]
Hi,

I like your plugin on atom and would like to have the following feature:

Show the full file path in the open recent menu - currently long paths are abbreviated which makes it sometimes in long path environments hard to see which was the correct file.

Regards
Stefan

**Comment by Zren** [comment]
abbreviated how? Screenshot?

**Comment by stebiger** [comment]
-- removed screenshot --

Sorry for blackening most of the paths but that's for protection of my customers.

Those dots can really make a mess if you are unsure what file it is if you have multiple environment setups.

Notepad++ shows the whole filepath - another idea would be to put the abbreviation somewhere in the middle of such long filepaths to have maybe the last 2 folder levels.

**Comment by Zren** [comment]
Hmm. Now the question is wither the menuitem is using `text-overflow: ellipsis` to hide the overflow when the menu reaches it's `max-width`, or if there's a hardcoded character limit. The latter would be easier than the former. I could do

``` js
if (menuItem.label.length > x) {
  menuItem.label = menuItem.label.substr(0, x/2 - 4) + '...' + menuItem.label.substr(-(x/2 - 4), -1)
}
```

If it's the former, then it might be a dynamic limit which 'd be a pain to discover how many characters are allowed. so options are:
1. A maximum character limit set in the config to put a ellipsis in the middle of the path.
2. Split the path like I was messing around with in #3 into a sublabel.

![](https://camo.githubusercontent.com/ab37aa00b905b4c22cb871cca4b8ceea130e6efb/687474703a2f2f692e696d6775722e636f6d2f434a386b4c78472e706e67)

I could put the last x characters in the top black label, and the first x characters in the gray bottom sublabel if the path > y characters.

**Comment by Zren** [comment]
So it's deffinitely cut off based on pixel count rather than characters (guesed as much). Trying to limit to 100 characters isn't very ideal since it might still cutoff at the end.

![](http://i.imgur.com/C9GXSXu.png)

Using a sublabel when over 100 chars, and showing the last 60 chars in the main label seems to work nice.

![](http://i.imgur.com/DFZAOg0.png)

It even works when the screen is 800x600 res (wasn't sure if the menu would shrink it's width).

![](http://i.imgur.com/z7cbUe2.png)

I made up the 100 char limit. I should probably test what's the best cutoff, but this should work for now.

Tell me if 2.3.0 works for you.

**Comment by stebiger** [comment]
Works good except that there is one entry in the upper region that is not displayed like it should:

![image](https://cloud.githubusercontent.com/assets/8200750/8644799/676caed0-2942-11e5-9793-c8a1759ec11b.png)

But others are working as intendend and I like it.

**Comment by stebiger** [comment]
After working a few days all entries are as expected in my menu.
