### ISSUE TITLE
Remove individual items from the recent lists

### ISSUE THREAD

**Issue by josh-egan** [Zren/atom-open-recent#9]
It would be really nice to be able to remove individual entries from the "Open Recent" dialog. There is a "Clear List" option, but I don't want to clear the entire list, I just want to remove a single entry.

**Comment by Zren** [comment]
I've thought about how to implement this in a simplified way. Having a submenu "Remove Item" in the menu is out. It's just bad UI design. I could migrate the array of paths from `localStorage` to Atom's config (since it can signal other windows now when there's a change). I'd have to migrate the data though.

The array of string editor widget for the settings view is [poorly designed](http://i.imgur.com/5h0EqRJ.png) for handling very long strings with spaces in them, but a user could open their `config.cson` and manually edit them from there.

**Comment by josh-egan** [comment]
Ya, I've been reading the atom api docs for the [menu manager](https://atom.io/docs/api/v1.0.2/MenuManager) and it doesn't look like the menu is very flexible. Is the `localStorage` editable - could I go in and edit that?

Btw, I really like the latest release that allows setting maxRecentFiles and maxRecentDirectories!

**Comment by Zren** [comment]
Yeah. `localStorage.openRecent` is a serialized JSON object as a string.

Ctrl+Alt+I (Toggle Dev Tools) then goto the console.

**Comment by josh-egan** [comment]
Great, thanks. Also, do you know if there's a way to refresh the open-recent package after I've modified the data? After modifying the data, I'm having to restart atom to get the changes to take effect.

**Comment by Zren** [comment]
Migrated paths to the `config.cson`.

**Comment by Zren** [comment]
Moved back to localStorage due to #12. Considering making a submenu to remove specific items.
